### obtener usuarios
GET http://localhost:3000/api/users


### obtener un usuario
GET http://localhost:3000/api/users/:id

### crear nuevo usuario
POST http://localhost:3000/api/users
Content-Type: application/json


### modificar datos de usuario (PUT)
PUT http://localhost:3000/api/users/:id
Content-Type: application/json

### modificar datos de usuario (POST)
PATCH http://localhost:3000/api/users/:id
Content-Type: application/json

### eliminar un usuario
DELETE http://localhost:3000/api/users/:id